# Generated by Django 3.2.8 on 2021-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211103_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.CharField(default='4 people', max_length=255),
        ),
    ]
