# Generated by Django 3.2.8 on 2021-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.ManyToManyField(related_name='qt', to='recipes.Quantity'),
        ),
    ]
