# Generated by Django 3.2.8 on 2021-11-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20211103_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
