# Generated by Django 3.2.8 on 2021-11-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20211103_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
