# Generated by Django 3.2.8 on 2021-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_preparation_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
